branches:
  only:
  - master

language: node_js

install:
- npm install hexo-cli -g

before_script:
- git config user.name "Chielo Newctle"
- git config user.email "ChieloNewctle@Yandex.com"
- sed -i'' "s~git@github.com:chielonewctle~https://$GITHUB_ACCESS_TOKEN@github.com/chielonewctle~" _config.yml

script:
- hexo generate
- hexo deploy
